name: Build and publish to Nexus

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'


    - name: Build with Maven
      run: mvn package --file pom.xml
      
    - name: Publish to Nexus
      uses: AbdulRahmanSayyad/nexus-repo-github-action@v1.0.0
      with:
        serverUrl: 'http://10.3.0.5:8081/'
        username: 'admin'
        password: 'Admin@123#'
        format: maven2
        repository: 'maven-releases'
        coordinates: groupId=com.example artifactId=my-project version=1.0.0
        assets: extension=jar
        filename: /target/my-project-1.0-SNAPSHOT.jar
