name: Build and publish to Nexus

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'


    - name: Build with Maven
      run: mvn clean package

    - name: Publish to Nexus
      uses: sonatype-nexus-community/nexus-repo-github-action@1.0.0
      with:
        serverUrl: 'http://10.3.0.5:8081/'
        username: 'admin'
        password: 'Admin@123#'
        repository: 'maven-releases'
        groupId: 'com.example'
        artifactId: 'my-project'
        version: '1.0.0'
        packaging: 'jar'
        file: 'target/my-project-1.0.0.jar'
